### ISSUE TITLE
We may not want to by default allow both `reshade-shaders` and `gshade-shaders`.

### ISSUE THREAD

**Issue by ultimatespirit** [cozyGalvinism/reshader#6]
We may not want to by default allow both `reshade-shaders` and `gshade-shaders`. If someone ends up with both directories in their area for whatever reason shaders will double load which is bad. Same story for textures.

_Originally posted by @ultimatespirit in https://github.com/cozyGalvinism/reshader/pull/3#discussion_r1110445145_

**Comment by cozyGalvinism** [comment]
Hmm... but some of the GShade Presets might need shaders that are not present in the ReShade shaders. So either the GShade and ReShade options become mutually exclusive or there needs to be some form of toggle

**Comment by cozyGalvinism** [comment]
This sort of ties in with #5 too. In the future, we might be able to support GShade presets with ReShade shaders.

**Comment by cozyGalvinism** [comment]
Implemented in cd1e442
